package.path = "./tests/?.lua;" .. package.path
local h = require("harness")

local function load()
  local LP = h.loadCore()
  h.load("LevelPace/Ledger.lua")
  h.load("LevelPace/Modifiers.lua")
  h.load("LevelPace/Rates.lua")
  h.load("LevelPace/History.lua")
  h.load("LevelPace/Estimator.lua")
  LP:InitDB()
  LP.History:Init()
  return LP
end

h.run("a fresh record is created for the current level", function()
  h.state.level = 71
  local LP = load()
  local r = LP.History:Current()
  h.eq(r.level, 71, "level")
  h.eq(r.killCount, 0, "no kills yet")
  h.eq(r.deaths, 0, "no deaths yet")
end)

h.run("kill XP accumulates into the kill bucket", function()
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 400 experience.")
  local r = LP.History:Current()
  h.eq(r.xpBySource.kill, 400, "kill bucket")
  h.eq(r.xpBySource.quest, 0, "quest bucket untouched")
  h.eq(r.killCount, 1, "kill counted")
  h.eq(r.baseXP, 400, "base accumulated")
end)

h.run("quest XP is bucketed separately from kills", function()
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 400 experience.")
  LP.Ledger:NoteQuestFinished(1, 1000)
  LP.Ledger:OnChat("You gain 5000 experience.")
  local r = LP.History:Current()
  h.eq(r.xpBySource.kill, 400, "kill")
  h.eq(r.xpBySource.quest, 5000, "quest")
  h.eq(r.killCount, 1, "one kill")
  h.eq(r.questCount, 1, "one quest")
end)

h.run("rested bonus is tracked and excluded from base", function()
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 800 experience. (+400 exp Rested bonus)")
  local r = LP.History:Current()
  h.eq(r.xpBySource.kill, 800, "total went in the bucket")
  h.eq(r.baseXP, 400, "base excludes the rested half")
  h.eq(r.restedConsumed, 400, "rested tracked")
end)

-- The gap is RECORDED, not filtered. Corpse runs and downtime still count.
h.run("largest gap is recorded but the clock keeps running", function()
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 100 experience.")
  h.advance(3600)
  LP.Ledger:OnChat("Ghoul dies, you gain 100 experience.")
  local r = LP.History:Current()
  h.near(r.largestGap, 3600, 1, "an hour gap recorded")
  h.near(r.elapsed, 3610, 1, "elapsed still includes it -- no sanitising")
end)

h.run("deaths and corpse runs are counted", function()
  local LP = load()
  LP.History:OnDeath()
  h.advance(90)
  LP.History:OnResurrect()
  local r = LP.History:Current()
  h.eq(r.deaths, 1, "death counted")
  h.near(r.corpseRunSeconds, 90, 1, "corpse run time counted, because it really cost you 90s")
end)

h.run("resurrect without a death does not corrupt the record", function()
  local LP = load()
  LP.History:OnResurrect()
  h.eq(LP.History:Current().corpseRunSeconds, 0, "no phantom time")
end)

h.run("level-up closes the record and opens a new one", function()
  h.state.level = 71
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 500 experience.")
  h.advance(50)
  LP.History:OnLevelUp(72)
  h.eq(#LP.History:All(), 1, "one completed level")
  local done = LP.History:Get(71)
  h.eq(done.level, 71, "archived level 71")
  h.near(done.elapsed, 60, 1, "elapsed captured")
  h.eq(done.xpBySource.kill, 500, "its xp preserved")
  local cur = LP.History:Current()
  h.eq(cur.level, 72, "new record for 72")
  h.eq(cur.killCount, 0, "fresh counters")
end)

h.run("MedianBaseRate is nil until a level completes", function()
  local LP = load()
  h.eq(LP.History:MedianBaseRate(), nil, "no completed levels")
end)

h.run("MedianBaseRate uses completed levels", function()
  h.state.level = 71
  local LP = load()
  h.advance(1)
  LP.Ledger:OnChat("Ghoul dies, you gain 1000 experience.")
  h.advance(99)
  LP.History:OnLevelUp(72)                       -- 1000 base over 100s = 10/s
  h.advance(1)
  LP.Ledger:OnChat("Ghoul dies, you gain 4000 experience.")
  h.advance(199)
  LP.History:OnLevelUp(73)                       -- 4000 base over 200s = 20/s
  h.near(LP.History:MedianBaseRate(), 15, 0.5, "median of 10 and 20")
end)

h.run("reset clears the current level but keeps completed ones", function()
  h.state.level = 71
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 500 experience.")
  LP.History:OnLevelUp(72)
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 700 experience.")
  h.eq(LP.History:Current().xpBySource.kill, 700, "accumulated")
  LP.History:Reset()
  h.eq(LP.History:Current().xpBySource.kill, 0, "current cleared")
  h.eq(#LP.History:All(), 1, "completed level preserved")
end)

h.run("kill XP samples feed the mobs-to-level range", function()
  local LP = load()
  for i = 1, 12 do
    h.advance(1)
    LP.Ledger:OnChat("Ghoul dies, you gain 100 experience.")
  end
  h.eq(#LP.History:KillXPSamples(), 12, "twelve samples")
  h.eq(LP.History:KillXPSamples()[1], 100, "base xp per kill")
end)

h.run("quest XP does not pollute the kill-xp samples", function()
  local LP = load()
  h.advance(1)
  LP.Ledger:NoteQuestFinished(1, 1000)
  LP.Ledger:OnChat("You gain 25000 experience.")
  h.eq(#LP.History:KillXPSamples(), 0, "a 25k turn-in must not become a 'mob'")
end)

h.run("ObservedFraction reflects progress through the level", function()
  h.state.xpMax = 1000
  local LP = load()
  h.advance(1)
  LP.Ledger:OnChat("Ghoul dies, you gain 250 experience.")
  h.near(LP.History:ObservedFraction(), 0.25, 0.01, "a quarter observed")
end)

h.run("Summarise reports the real mix", function()
  h.state.level = 71
  local LP = load()
  h.advance(1)
  LP.Ledger:OnChat("Ghoul dies, you gain 300 experience.")
  LP.Ledger:NoteQuestFinished(1, 100)
  LP.Ledger:OnChat("You gain 700 experience.")
  h.advance(99)
  LP.History:OnLevelUp(72)
  local s = LP.History:Summarise(LP.History:Get(71))
  h.eq(s.total, 1000, "total")
  h.near(s.questShare, 0.7, 0.001, "70% from quests")
  h.near(s.killShare, 0.3, 0.001, "30% from kills")
end)


-- ==== live view (reported bug: display only moved on XP gain) ====

h.run("elapsed advances with the clock, not only on XP events", function()
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 100 experience.")
  local atGain = LP.History:Elapsed()
  h.advance(300)
  h.near(LP.History:Elapsed(), atGain + 300, 1, "five idle minutes are counted immediately")
end)

h.run("the live rate DECAYS while idle", function()
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 1000 experience.")
  local r1 = LP.History:LiveBaseRate()
  h.near(r1, 100, 1, "1000 base over 10s")
  h.advance(90)
  local r2 = LP.History:LiveBaseRate()
  h.near(r2, 10, 0.5, "same 1000 base over 100s -- the rate fell without any new event")
  h.ok(r2 < r1, "idle time pushes the rate down")
end)

h.run("live rate is nil before any XP", function()
  local LP = load()
  h.advance(60)
  h.eq(LP.History:LiveBaseRate(), nil, "no XP means no rate, not zero")
end)

h.run("BaseRateSamples reflects the live value", function()
  local LP = load()
  h.advance(10)
  LP.Ledger:OnChat("Ghoul dies, you gain 1000 experience.")
  h.eq(#LP.History:BaseRateSamples(), 1, "one live value")
  h.advance(90)
  h.near(LP.History:BaseRateSamples()[1], 10, 0.5, "and it is recomputed, not cached")
end)

os.exit(h.report() and 0 or 1)
