-- LevelPace :: Modules/Nemesis
--
-- Battleground awareness: who just joined, who left, who keeps killing you,
-- who has the flag, and what your record actually is.
--
-- Two things are worth knowing before reading this.
--
-- 1. The enemy roster comes from the battleground scoreboard, which lists
--    BOTH factions. It is polled, not pushed, so a departure is inferred from
--    absence -- and absence flickers, so it takes two consecutive misses.
--
-- 2. Flag events have NO GlobalStrings on 3.3.5a. The text is generated by the
--    server and arrives as ordinary chat, so the patterns below are literal
--    English and will not fire on a non-English or reworded server. The
--    language-independent source is GetBattlefieldFlagPosition, which gives
--    position but no name; chat is what supplies the carrier.

local LP = _G.LevelPace
LP.Nemesis = LP.Nemesis or {}
local N = LP.Nemesis

local util = LP.util

-- Scoreboard faction ids (WorldStateFrame.lua): 0 = Horde, 1 = Alliance.
local FACTION_HORDE, FACTION_ALLIANCE = 0, 1

-- Two consecutive misses before we call someone gone.
local MISSES_BEFORE_LEFT = 2

local SOUND = "Sound\\Interface\\RaidWarning.wav"

local function db()
  if not LP.db then return nil end
  local d = LP.db.nemesis
  if not d then
    d = {
      enemies = {},          -- name -> { kills, deaths, guild }
      longestStreak = 0,
      results = {},          -- bgID -> { wins, losses }
      sounds = {
        joined = false, nemesis = true, flag = true,
        kill = false, death = false, streak = true,
      },
    }
    LP.db.nemesis = d
  end
  d.enemies = d.enemies or {}
  d.results = d.results or {}
  d.sounds = d.sounds or {}
  d.longestStreak = d.longestStreak or 0
  return d
end

-- Session-local. A killstreak in progress means nothing after a logout, and
-- roster state describes one match.
local currentStreak = 0
local roster = {}       -- name -> misses since last seen
local seenRoster = false

function N:Init()
  currentStreak = 0
  roster = {}
  seenRoster = false
  db()
end

-- ---------------------------------------------------------------------------
-- Roster
-- ---------------------------------------------------------------------------

local function enemyFaction()
  local mine = UnitFactionGroup and UnitFactionGroup("player")
  -- If we cannot tell, assume Alliance so enemies read as Horde rather than
  -- silently returning an empty enemy list.
  if mine == "Horde" then return FACTION_ALLIANCE end
  return FACTION_HORDE
end

function N:ScanEnemies()
  local out = {}
  if not GetNumBattlefieldScores or not GetBattlefieldScore then return out end
  local want = enemyFaction()
  for i = 1, GetNumBattlefieldScores() do
    -- TWELVE returns on 3.3.5a; faction is 6, rank 7, classToken 10.
    local name, kb, hk, deaths, honor, faction, _, _, _, classToken =
      GetBattlefieldScore(i)
    if name and faction == want then
      out[name] = {
        killingBlows = kb or 0,
        honorableKills = hk or 0,
        deaths = deaths or 0,
        classToken = classToken,
      }
    end
  end
  return out
end

function N:PollRoster()
  if RequestBattlefieldScoreData then RequestBattlefieldScoreData() end
  local now = self:ScanEnemies()
  local joined, left = {}, {}

  for name in pairs(now) do
    if roster[name] == nil then
      joined[#joined + 1] = name
    end
    roster[name] = 0                      -- present: reset the miss counter
  end

  for name, misses in pairs(roster) do
    if now[name] == nil then
      misses = misses + 1
      if misses >= MISSES_BEFORE_LEFT then
        left[#left + 1] = name
        roster[name] = nil
      else
        roster[name] = misses
      end
    end
  end

  table.sort(joined)
  table.sort(left)

  -- The first scan is the whole enemy team arriving at once. Announcing all
  -- fifteen as "joined" is noise, so the generic line is suppressed -- but a
  -- NEMESIS is announced either way. "Your arch nemesis is in this match" is
  -- the single most useful thing this module can tell you, and it is most
  -- useful at the start, not only if they happen to reconnect later.
  local firstScan = not seenRoster
  seenRoster = true

  for i = 1, #joined do
    local name = joined[i]
    LP:Fire("ENEMY_JOINED", name)
    if self:IsNemesis(name) then
      LP:Fire("NEMESIS_SPOTTED", name)
      self:Alert("nemesis", name .. " is here")
    elseif not firstScan then
      self:Alert("joined", name .. " joined")
    end
  end
  for i = 1, #left do
    LP:Fire("ENEMY_LEFT", left[i])
  end

  return joined, left
end

-- ---------------------------------------------------------------------------
-- Kills, deaths, streaks
-- ---------------------------------------------------------------------------

function N:Record(name)
  local d = db()
  if not d or not name then return nil end
  d.enemies[name] = d.enemies[name] or { kills = 0, deaths = 0 }
  return d.enemies[name]
end

function N:RecordKill(name)
  local r = self:Record(name)
  if not r then return end
  r.kills = r.kills + 1
  currentStreak = currentStreak + 1
  local d = db()
  if currentStreak > d.longestStreak then
    d.longestStreak = currentStreak
    self:Alert("streak", "New best killstreak: " .. currentStreak)
  end
  LP:Fire("NEMESIS_KILL", name, currentStreak)
  self:Alert("kill", "Killed " .. name)
end

function N:RecordDeath(name)
  local r = self:Record(name)
  if r then r.deaths = r.deaths + 1 end
  currentStreak = 0
  LP:Fire("NEMESIS_DEATH", name)
  self:Alert("death", name and ("Killed by " .. name) or "Died")
end

function N:CurrentStreak() return currentStreak end
function N:LongestStreak() local d = db(); return (d and d.longestStreak) or 0 end

function N:IsNemesis(name)
  local d = db()
  local r = d and d.enemies[name]
  if not r then return false end
  return (r.deaths or 0) > (r.kills or 0)
end

function N:TopNemeses(n)
  local d = db()
  local out = {}
  if not d then return out end
  for name, r in pairs(d.enemies) do
    local net = (r.deaths or 0) - (r.kills or 0)
    if net > 0 then
      out[#out + 1] = { name = name, net = net, kills = r.kills, deaths = r.deaths,
                        guild = r.guild }
    end
  end
  table.sort(out, function(a, b)
    if a.net ~= b.net then return a.net > b.net end
    return a.name < b.name          -- stable, so the list does not jitter
  end)
  while #out > (n or 3) do table.remove(out) end
  return out
end

-- ---------------------------------------------------------------------------
-- Guilds
--
-- GetGuildInfo takes a UNIT token and 3.3.5a has no nameplate tokens, so this
-- only ever learns guilds for enemies you target, mouse over, or focus. The
-- coverage figure exists so the UI can say "6 of 15" instead of implying the
-- rest have no guild.
-- ---------------------------------------------------------------------------

function N:LearnGuild(unit)
  if not GetGuildInfo or not UnitName then return nil end
  local guild = GetGuildInfo(unit)
  if not guild then return nil end
  local name = UnitName(unit)
  if not name then return nil end
  local r = self:Record(name)
  if r then r.guild = guild end
  return guild
end

function N:GuildOf(name)
  local d = db()
  local r = d and d.enemies[name]
  return r and r.guild or nil
end

function N:GuildCoverage()
  local known, total = 0, 0
  for name in pairs(roster) do
    total = total + 1
    if self:GuildOf(name) then known = known + 1 end
  end
  return known, total
end

-- ---------------------------------------------------------------------------
-- Flags
--
-- Literal English substrings: 3.3.5a ships NO GlobalStrings for these, so
-- there is nothing to build a locale-correct pattern from.
-- ---------------------------------------------------------------------------

local FLAG_PATTERNS = {
  { action = "taken",    pat = "[Ff]lag was picked up by (.+)!" },
  { action = "captured", pat = "[Ff]lag was captured by (.+)!" },
  { action = "returned", pat = "[Ff]lag was returned to its base by (.+)!" },
  { action = "dropped",  pat = "[Ff]lag was dropped by (.+)!" },
}

function N:OnBGChat(msg)
  if type(msg) ~= "string" or msg == "" then return nil end
  for i = 1, #FLAG_PATTERNS do
    local p = FLAG_PATTERNS[i]
    local who = string.match(msg, p.pat)
    if who then
      local e = { action = p.action, who = who, text = msg }
      LP:Fire("BG_FLAG", e)
      self:Alert("flag", msg)
      return e
    end
  end
  return nil
end

-- ---------------------------------------------------------------------------
-- Lifetime statistics
--
-- Honorable kills are genuinely lifetime: the server sends them. Win/loss is
-- only what we have watched since install, and must never be presented as if
-- it were the character's whole history.
-- ---------------------------------------------------------------------------

function N:RecordResult(bgID, won)
  local d = db()
  if not d or not bgID then return end
  d.results[bgID] = d.results[bgID] or { wins = 0, losses = 0 }
  if won then
    d.results[bgID].wins = d.results[bgID].wins + 1
  else
    d.results[bgID].losses = d.results[bgID].losses + 1
  end
end

function N:Lifetime()
  local d = db()
  local hk = 0
  if GetPVPLifetimeStats then hk = (GetPVPLifetimeStats()) or 0 end
  local wins, losses = 0, 0
  local byBG = {}
  if d then
    for id, r in pairs(d.results) do
      wins = wins + (r.wins or 0)
      losses = losses + (r.losses or 0)
      byBG[id] = { wins = r.wins or 0, losses = r.losses or 0 }
    end
  end
  return {
    honorableKills = hk,
    honorableKillsAreLifetime = true,
    wins = wins,
    losses = losses,
    -- Deliberately explicit. A player who has been 80 for a year and installed
    -- this yesterday must not be shown "3 wins" as their career record.
    winsAreLifetime = false,
    byBG = byBG,
    longestStreak = self:LongestStreak(),
  }
end

-- ---------------------------------------------------------------------------
-- Alerts
-- ---------------------------------------------------------------------------

function N:Alert(kind, msg)
  local d = db()
  if not d then return end
  if msg then LP:Print(msg) end
  if d.sounds[kind] and PlaySoundFile then
    -- PlaySoundFile returns nothing on 3.3.5a: a bad path fails silently and
    -- there is no way to detect it, which is why the path is a constant.
    PlaySoundFile(SOUND)
  end
end

-- ---------------------------------------------------------------------------
-- Module
-- ---------------------------------------------------------------------------

local POLL_SECONDS = 3

LP:RegisterModule({
  id = "nemesis",
  title = "Nemesis",
  desc = "Battleground roster, nemesis alerts, flags, kills and streaks.",
  default = true,

  OnEnable = function()
    N:Init()

    LP:OnCombatLog("nemesis", { "PARTY_KILL" }, function(_, _, _, _, _, _, dstName)
      -- PARTY_KILL fires for the KILLER only and is unicast to their group:
      -- the victim never sees it, so this is our kill, not someone else's.
      if dstName then N:RecordKill(dstName) end
    end)

    LP:RegisterEvent("PLAYER_DEAD", "nemesis", function()
      N:RecordDeath(N.lastAttacker)
    end)

    LP:RegisterEvent("PLAYER_TARGET_CHANGED", "nemesis", function()
      N:LearnGuild("target")
    end)
    LP:RegisterEvent("UPDATE_MOUSEOVER_UNIT", "nemesis", function()
      N:LearnGuild("mouseover")
    end)

    for _, ev in ipairs({ "CHAT_MSG_BG_SYSTEM_ALLIANCE",
                          "CHAT_MSG_BG_SYSTEM_HORDE",
                          "CHAT_MSG_BG_SYSTEM_NEUTRAL" }) do
      LP:RegisterEvent(ev, "nemesis", function(msg) N:OnBGChat(msg) end)
    end

    LP:RegisterEvent("PLAYER_ENTERING_BATTLEGROUND", "nemesis", function()
      N:Init()
    end)

    -- Arenas share the scoreboard API but not the point of any of this.
    N.pollJob = LP:Schedule(POLL_SECONDS, function()
      if IsActiveBattlefieldArena and IsActiveBattlefieldArena() then return end
      if not GetNumBattlefieldScores or GetNumBattlefieldScores() == 0 then return end
      N:PollRoster()
    end)
  end,

  OnDisable = function()
    -- The event router drops the handlers; the polling job is ours to stop.
    if N.pollJob then LP:Unschedule(N.pollJob); N.pollJob = nil end
  end,
})
