-- LevelPace :: Modules/Nemesis
--
-- Battleground awareness: who just joined, who left, who keeps killing you,
-- who has the flag, and what your record actually is.
--
-- Two things are worth knowing before reading this.
--
-- 1. The enemy roster comes from the battleground scoreboard, which lists
--    BOTH factions. It is polled, not pushed, so a departure is inferred from
--    absence -- and absence flickers, so it takes two consecutive misses.
--
-- 2. Flag events have NO GlobalStrings on 3.3.5a. The text is generated by the
--    server and arrives as ordinary chat, so the patterns below are literal
--    English and will not fire on a non-English or reworded server. The
--    language-independent source is GetBattlefieldFlagPosition, which gives
--    position but no name; chat is what supplies the carrier.

local LP = _G.LevelPace
LP.Nemesis = LP.Nemesis or {}
local N = LP.Nemesis

local util = LP.util

-- Scoreboard faction ids (WorldStateFrame.lua): 0 = Horde, 1 = Alliance.
local FACTION_HORDE, FACTION_ALLIANCE = 0, 1

-- Two consecutive misses before we call someone gone.
local MISSES_BEFORE_LEFT = 2

local SOUND = "Sound\\Interface\\RaidWarning.wav"

-- Below this, a "new best" is noise on a fresh install rather than news.
local MIN_STREAK_TO_ANNOUNCE = 3
-- The match log shown in the meter's "BG log" view. Session-local, one match.
local MAX_LOG = 300
-- The class icon sheet the 3.3.5a scoreboard itself draws from
-- (WorldStateFrame.lua:665, with the CLASS_ICON_TCOORDS layout), and the LFG
-- role icons, as inline texture escapes: the meter rows are font strings, and
-- Blizzard's own frames embed these the same way (LFDFrame.lua:1097).
-- Coordinates are pixels of the sheet.
local CLASS_SHEET = "Interface\\WorldStateFrame\\Icons-Classes"
local ROLE_ICON = {
  healer = "|TInterface\\LFGFrame\\UI-LFG-ICON-PORTRAITROLES:14:14:0:0:64:64:20:39:1:20|t",
  damage = "|TInterface\\LFGFrame\\UI-LFG-ICON-PORTRAITROLES:14:14:0:0:64:64:20:39:22:41|t",
}
local LOG_COLOUR = {
  joined  = { r = 0.12, g = 1.00, b = 0.00 }, left    = { r = 0.62, g = 0.62, b = 0.62 },
  flag    = { r = 1.00, g = 0.50, b = 0.00 }, kill    = { r = 0.12, g = 1.00, b = 0.00 },
  death   = { r = 1.00, g = 0.25, b = 0.25 }, nemesis = { r = 0.64, g = 0.21, b = 0.93 },
  result  = { r = 0.90, g = 0.80, b = 0.50 }, match   = { r = 0.62, g = 0.62, b = 0.62 },
}

local function db()
  if not LP.db then return nil end
  local d = LP.db.nemesis
  if not d then
    d = {
      enemies = {},          -- name -> { kills, deaths, guild }
      longestStreak = 0,
      results = {},          -- bgID -> { wins, losses }
      sounds = {
        joined = false, nemesis = true, flag = true,
        kill = false, death = false, streak = true,
      },
    }
    LP.db.nemesis = d
  end
  d.enemies = d.enemies or {}
  d.results = d.results or {}
  d.sounds = d.sounds or {}
  d.longestStreak = d.longestStreak or 0
  return d
end

-- Are we in a battleground at all? Asked BEFORE the scoreboard has anything
-- in it, which is exactly when it matters: the scoreboard is empty until
-- something requests it from the server.
function N:InBattleground()
  if IsActiveBattlefieldArena and IsActiveBattlefieldArena() then return false end
  if IsInInstance then
    local _, kind = IsInInstance()
    if kind == "pvp" then return true end
    if kind ~= nil then return false end
  end
  return (GetNumBattlefieldScores and GetNumBattlefieldScores() > 0) or false
end

-- Session-local. A killstreak in progress means nothing after a logout, and
-- roster state describes one match.
local currentStreak = 0
local roster = {}       -- name -> misses since last seen
local teamRoster = {}   -- same, for your own side (log only, no alerts)
local seenRoster = false
local matchRecorded = false   -- this match's result already written
local unattributedDeaths = 0  -- died in a BG with no player on the last hit
N.log = N.log or {}           -- this match's events, oldest first
N.people = N.people or {}     -- name -> class, faction, role from the scoreboard

function N:Init()
  currentStreak = 0
  roster = {}
  seenRoster = false
  -- A match that is already over when we arrive -- a /reload on the final
  -- scoreboard, or joining late -- was not watched, so it is not counted.
  matchRecorded = (GetBattlefieldWinner and GetBattlefieldWinner() ~= nil) or false
  teamRoster = {}
  unattributedDeaths = 0
  self.log = {}
  self.people = {}
  db()
end

-- ---------------------------------------------------------------------------
-- Roster
-- ---------------------------------------------------------------------------

-- Which side am I on, as the scoreboard sees it (0 Horde, 1 Alliance).
--
-- NOT UnitFactionGroup("player"). Private servers run "mercenary mode": an
-- Alliance character fills a Horde slot and plays FOR the Horde, and the
-- scoreboard lists them under the Horde. Every "my team" question is answered
-- by the row with my own name; the character's home faction is only the
-- fallback for the moment before the scoreboard has arrived.
function N:MyTeam()
  local me = UnitName and UnitName("player") or nil
  if me and GetNumBattlefieldScores and GetBattlefieldScore then
    for i = 1, GetNumBattlefieldScores() do
      local name, _, _, _, _, faction = GetBattlefieldScore(i)
      -- Cross-realm rows carry "Name-Realm".
      if name and (name == me or string.match(name, "^([^%-]+)") == me) and faction ~= nil then
        return faction
      end
    end
  end
  local mine = UnitFactionGroup and UnitFactionGroup("player")
  if mine == "Horde" then return FACTION_HORDE end
  return FACTION_ALLIANCE
end

local function enemyFaction()
  if N:MyTeam() == FACTION_HORDE then return FACTION_ALLIANCE end
  return FACTION_HORDE
end

function N:ScanEnemies()
  local out = {}
  if not GetNumBattlefieldScores or not GetBattlefieldScore then return out end
  local want = enemyFaction()
  for i = 1, GetNumBattlefieldScores() do
    -- TWELVE returns on 3.3.5a; faction is 6, rank 7, classToken 10.
    local name, kb, hk, deaths, honor, faction, _, _, _, classToken =
      GetBattlefieldScore(i)
    if name and faction == want then
      out[name] = {
        killingBlows = kb or 0,
        honorableKills = hk or 0,
        deaths = deaths or 0,
        classToken = classToken,
      }
    end
  end
  return out
end

-- Everyone on the scoreboard, both sides: what the log needs to colour a name
-- and put a class next to it. Role is INFERRED -- healing above damage means
-- healer -- because 3.3.5a's scoreboard carries class but never spec, and an
-- enemy cannot be inspected.
function N:ScanAll()
  -- Merged into what is already known, never replaced: someone who LEAVES
  -- drops off the scoreboard, and the log line saying so is exactly when
  -- their class and colour are wanted. Cleared per match in Init.
  local people = self.people or {}
  if not GetNumBattlefieldScores or not GetBattlefieldScore then self.people = people; return people end
  for i = 1, GetNumBattlefieldScores() do
    local name, kb, _, deaths, _, faction, _, _, _, classToken, damage, healing =
      GetBattlefieldScore(i)
    if name then
      damage, healing = damage or 0, healing or 0
      local role = nil
      if healing > 0 and healing > damage then role = "healer"
      elseif damage > 0 then role = "damage" end
      people[name] = { classToken = classToken, faction = faction, role = role,
                       damage = damage, healing = healing,
                       killingBlows = kb or 0, deaths = deaths or 0 }
    end
  end
  self.people = people
  return people
end

function N:Identity(name)
  return name and self.people and self.people[name] or nil
end

-- Present/absent diff with the two-miss rule, for either side's roster.
local function diffRoster(tbl, present)
  local joined, left = {}, {}
  for name in pairs(present) do
    if tbl[name] == nil then joined[#joined + 1] = name end
    tbl[name] = 0                         -- present: reset the miss counter
  end
  for name, misses in pairs(tbl) do
    if present[name] == nil then
      misses = misses + 1
      if misses >= MISSES_BEFORE_LEFT then
        left[#left + 1] = name
        tbl[name] = nil
      else
        tbl[name] = misses
      end
    end
  end
  table.sort(joined)
  table.sort(left)
  return joined, left
end

function N:PollRoster()
  self:ScanAll()
  local now = self:ScanEnemies()
  local joined, left = diffRoster(roster, now)

  local team = {}
  for _, r in ipairs(self:ScanTeam()) do team[r.name] = true end
  local teamJoined, teamLeft = diffRoster(teamRoster, team)

  -- The first scan is the whole enemy team arriving at once. Announcing all
  -- fifteen as "joined" is noise, so the generic line is suppressed -- but a
  -- NEMESIS is announced either way. "Your arch nemesis is in this match" is
  -- the single most useful thing this module can tell you, and it is most
  -- useful at the start, not only if they happen to reconnect later.
  local firstScan = not seenRoster
  seenRoster = true
  -- Logged at the first real scan, not on the entering event: by now the
  -- zone name is the battleground's, not the one we ported out of.
  if firstScan then
    self:Log("match", nil, "Entered " .. ((GetRealZoneText and GetRealZoneText()) or "the battleground"))
  end

  for i = 1, #joined do
    local name = joined[i]
    LP:Fire("ENEMY_JOINED", name)
    if self:IsNemesis(name) then
      LP:Fire("NEMESIS_SPOTTED", name)
      self:Alert("nemesis", name .. " is here")
      self:Log("nemesis", name, name .. " (your nemesis) is here")
    elseif not firstScan then
      self:Alert("joined", name .. " joined")
      self:Log("joined", name, name .. " joined")
    end
  end
  for i = 1, #left do
    LP:Fire("ENEMY_LEFT", left[i])
    self:Log("left", left[i], left[i] .. " left")
  end
  -- Your own side is logged, never announced: fifteen "joined" lines about
  -- your own team at the start of a match is noise.
  if not firstScan then
    for i = 1, #teamJoined do self:Log("joined", teamJoined[i], teamJoined[i] .. " joined your team") end
  end
  for i = 1, #teamLeft do self:Log("left", teamLeft[i], teamLeft[i] .. " left your team") end

  return joined, left
end

-- ---------------------------------------------------------------------------
-- The match log
-- ---------------------------------------------------------------------------

-- Match clock as the scoreboard shows it. Milliseconds (WorldStateFrame.lua:824).
local function matchClock()
  local ms = GetBattlefieldInstanceRunTime and GetBattlefieldInstanceRunTime() or 0
  if not ms or ms <= 0 then return nil end
  local s = math.floor(ms / 1000)
  return string.format("%d:%02d", math.floor(s / 60), s % 60)
end

function N:Log(kind, who, text)
  local e = { kind = kind, who = who, text = text, at = matchClock(),
              t = (GetTime and GetTime()) or 0 }
  local id = self:Identity(who)
  if id then e.classToken, e.faction, e.role = id.classToken, id.faction, id.role end
  self.log[#self.log + 1] = e
  while #self.log > MAX_LOG do table.remove(self.log, 1) end
  LP:Fire("BG_LOG", e)
  return e
end

function N:LogEntries() return self.log end
function N:LogColour(kind) return LOG_COLOUR[kind] end
function N:UnattributedDeaths() return unattributedDeaths end

function N:ClassIcon(token)
  local c = token and CLASS_ICON_TCOORDS and CLASS_ICON_TCOORDS[token]
  if not c then return "" end
  return string.format("|T%s:14:14:0:0:256:256:%d:%d:%d:%d|t", CLASS_SHEET,
    math.floor(c[1] * 256 + 0.5), math.floor(c[2] * 256 + 0.5),
    math.floor(c[3] * 256 + 0.5), math.floor(c[4] * 256 + 0.5))
end

function N:ColourName(name, token)
  local col = token and RAID_CLASS_COLORS and RAID_CLASS_COLORS[token]
  if not col then return name end
  return string.format("|cff%02x%02x%02x%s|r",
    math.floor(col.r * 255 + 0.5), math.floor(col.g * 255 + 0.5),
    math.floor(col.b * 255 + 0.5), name)
end

-- The server's own sentence, with the player's name replaced by class icon,
-- role icon and class-coloured name. Plain find: names have no pattern chars,
-- but a name is never treated as a pattern regardless.
function N:Describe(e)
  local text = e.text or ""
  local who = e.who
  if not who then return text end
  local tag = self:ClassIcon(e.classToken) .. (ROLE_ICON[e.role or ""] or "")
              .. self:ColourName(who, e.classToken)
  -- Whole word only: "Ali" must not be found inside "Alliance". Plain find,
  -- then both edges are checked; the last whole-word hit wins because the
  -- server's sentences end with the name.
  local best, init = nil, 1
  while true do
    local s, f = string.find(text, who, init, true)
    if not s then break end
    local before = (s > 1) and string.sub(text, s - 1, s - 1) or " "
    local after = string.sub(text, f + 1, f + 1)
    if not string.find(before, "%w") and (after == "" or not string.find(after, "%w")) then
      best = { s, f }
    end
    init = f + 1
  end
  if not best then return text end
  return string.sub(text, 1, best[1] - 1) .. tag .. string.sub(text, best[2] + 1)
end

-- ---------------------------------------------------------------------------
-- Live team ranking
--
-- Where you sit against YOUR OWN TEAM in the battleground you are in right
-- now, coloured with the same bands as every other board.
--
-- Damage is ranked against every teammate, because everyone deals some.
-- Healing is ranked only against teammates who actually healed: ranking a
-- rogue's zero healing against fifteen other zeroes produces a number that
-- looks like information and is not. Each result carries the population it
-- was measured against so the UI can say "3rd of 9" rather than implying the
-- whole team was the field.
-- ---------------------------------------------------------------------------

function N:ScanTeam()
  local out = {}
  if not GetNumBattlefieldScores or not GetBattlefieldScore then return out end
  local want = self:MyTeam()
  for i = 1, GetNumBattlefieldScores() do
    -- damageDone is return 11, healingDone is 12 (WorldStateFrame.lua:662).
    local name, kb, _, deaths, _, faction, _, _, _, _, damage, healing =
      GetBattlefieldScore(i)
    if name and faction == want then
      out[#out + 1] = {
        name = name, killingBlows = kb or 0, deaths = deaths or 0,
        damage = damage or 0, healing = healing or 0,
      }
    end
  end
  return out
end

local function rankWithin(rows, field, meName, requireNonZero)
  local values, mine = {}, nil
  for i = 1, #rows do
    local v = rows[i][field] or 0
    if rows[i].name == meName then mine = v end
    if (not requireNonZero) or v > 0 then values[#values + 1] = v end
  end
  if mine == nil then return nil end
  if requireNonZero and mine <= 0 then
    -- Not part of this population, and saying "bottom" would be misleading.
    return { value = 0, pct = nil, band = nil, of = #values, participating = false }
  end
  local pct = LP.util.RankPercentile(mine, values)
  local place = 1
  for i = 1, #values do if values[i] > mine then place = place + 1 end end
  return {
    value = mine, pct = pct, of = #values, place = place, participating = true,
    band = pct and LP.data and LP.data.BandFor and LP.data.BandFor(pct) or nil,
  }
end

function N:TeamRanking()
  local rows = self:ScanTeam()
  if #rows == 0 then return nil end
  local me = UnitName and UnitName("player") or nil
  if not me then return nil end
  return {
    teamSize = #rows,
    damage  = rankWithin(rows, "damage",  me, false),
    healing = rankWithin(rows, "healing", me, true),
    kills   = rankWithin(rows, "killingBlows", me, false),
  }
end

-- ---------------------------------------------------------------------------
-- Kills, deaths, streaks
-- ---------------------------------------------------------------------------

function N:Record(name)
  local d = db()
  if not d or not name then return nil end
  d.enemies[name] = d.enemies[name] or { kills = 0, deaths = 0 }
  return d.enemies[name]
end

function N:RecordKill(name)
  local r = self:Record(name)
  if not r then return end
  r.kills = r.kills + 1
  currentStreak = currentStreak + 1
  local d = db()
  if currentStreak > d.longestStreak then
    d.longestStreak = currentStreak
    -- On a fresh install every one of the first few kills is a "new best",
    -- which is noise rather than news. Only shout once it is worth shouting.
    if currentStreak >= MIN_STREAK_TO_ANNOUNCE then
      self:Alert("streak", "New best killstreak: " .. currentStreak)
    end
  end
  LP:Fire("NEMESIS_KILL", name, currentStreak)
  self:Alert("kill", "Killed " .. name)
  self:Log("kill", name, "You killed " .. name)
end

function N:RecordDeath(name)
  local r = self:Record(name)
  if r then r.deaths = r.deaths + 1 end
  currentStreak = 0
  if name then
    self:Log("death", name, name .. " killed you")
  elseif self:InBattleground() then
    -- A pet, a totem, or fall damage: nobody to blame, but the death is real
    -- and the empty nemesis list must be able to explain itself.
    unattributedDeaths = unattributedDeaths + 1
    self:Log("death", nil, "You died (no player landed the last hit)")
  end
  LP:Fire("NEMESIS_DEATH", name)
  self:Alert("death", name and ("Killed by " .. name) or "Died")
end

function N:CurrentStreak() return currentStreak end
function N:LongestStreak() local d = db(); return (d and d.longestStreak) or 0 end

function N:IsNemesis(name)
  local d = db()
  local r = d and d.enemies[name]
  if not r then return false end
  return (r.deaths or 0) > (r.kills or 0)
end

function N:TopNemeses(n)
  local d = db()
  local out = {}
  if not d then return out end
  for name, r in pairs(d.enemies) do
    local net = (r.deaths or 0) - (r.kills or 0)
    if net > 0 then
      out[#out + 1] = { name = name, net = net, kills = r.kills, deaths = r.deaths,
                        guild = r.guild }
    end
  end
  table.sort(out, function(a, b)
    if a.net ~= b.net then return a.net > b.net end
    return a.name < b.name          -- stable, so the list does not jitter
  end)
  while #out > (n or 3) do table.remove(out) end
  return out
end

-- ---------------------------------------------------------------------------
-- Guilds
--
-- GetGuildInfo takes a UNIT token and 3.3.5a has no nameplate tokens, so this
-- only ever learns guilds for enemies you target, mouse over, or focus. The
-- coverage figure exists so the UI can say "6 of 15" instead of implying the
-- rest have no guild.
-- ---------------------------------------------------------------------------

function N:LearnGuild(unit)
  if not GetGuildInfo or not UnitName then return nil end
  local guild = GetGuildInfo(unit)
  if not guild then return nil end
  local name = UnitName(unit)
  if not name then return nil end
  local r = self:Record(name)
  if r then r.guild = guild end
  return guild
end

function N:GuildOf(name)
  local d = db()
  local r = d and d.enemies[name]
  return r and r.guild or nil
end

function N:GuildCoverage()
  local known, total = 0, 0
  for name in pairs(roster) do
    total = total + 1
    if self:GuildOf(name) then known = known + 1 end
  end
  return known, total
end

-- ---------------------------------------------------------------------------
-- Flags
--
-- Literal English substrings: 3.3.5a ships NO GlobalStrings for these, so
-- there is nothing to build a locale-correct pattern from.
-- ---------------------------------------------------------------------------

local FLAG_PATTERNS = {
  { action = "taken",    pat = "[Ff]lag was picked up by (.+)!" },
  { action = "captured", pat = "[Ff]lag was captured by (.+)!" },
  { action = "returned", pat = "[Ff]lag was returned to its base by (.+)!" },
  { action = "dropped",  pat = "[Ff]lag was dropped by (.+)!" },
}

function N:OnBGChat(msg)
  if type(msg) ~= "string" or msg == "" then return nil end
  for i = 1, #FLAG_PATTERNS do
    local p = FLAG_PATTERNS[i]
    local who = string.match(msg, p.pat)
    if who then
      local e = { action = p.action, who = who, text = msg }
      LP:Fire("BG_FLAG", e)
      self:Alert("flag", msg)
      self:Log("flag", who, msg)
      return e
    end
  end
  return nil
end

-- ---------------------------------------------------------------------------
-- Lifetime statistics
--
-- Honorable kills are genuinely lifetime: the server sends them. Win/loss is
-- only what we have watched since install, and must never be presented as if
-- it were the character's whole history.
-- ---------------------------------------------------------------------------

function N:RecordResult(bgID, won)
  local d = db()
  if not d or not bgID then return end
  d.results[bgID] = d.results[bgID] or { wins = 0, losses = 0 }
  if won then
    d.results[bgID].wins = d.results[bgID].wins + 1
  else
    d.results[bgID].losses = d.results[bgID].losses + 1
  end
end

-- Numbers only: the live ranking carries colour tables, which have no
-- business in SavedVariables. The band is recomputed from pct on display.
local function slim(r)
  if not r then return nil end
  return { value = r.value, pct = r.pct, place = r.place, of = r.of,
           participating = r.participating }
end

-- The end of a match, read the way Blizzard's own scoreboard reads it
-- (WorldStateFrame.lua:513): GetBattlefieldWinner() is nil until there is a
-- victor, then 0 for Horde and 1 for Alliance -- and it stays set on every
-- UPDATE_BATTLEFIELD_SCORE until you leave, so this must record exactly once.
-- Nothing called RecordResult before this existed: a player who won a match
-- saw "0W 0L since install" forever.
function N:CheckWinner()
  if matchRecorded or not GetBattlefieldWinner then return nil end
  local winner = GetBattlefieldWinner()
  if winner == nil then return nil end
  if IsActiveBattlefieldArena and IsActiveBattlefieldArena() then return nil end
  matchRecorded = true
  -- The side I played FOR, which under mercenary mode is not my faction.
  local won = (winner == self:MyTeam())
  local bg = (GetRealZoneText and GetRealZoneText()) or "unknown"
  self:RecordResult(bg, won)
  self:Log("result", nil, won and "Victory" or "Defeat")
  -- Keep the final standing. The live meters vanish with the scoreboard the
  -- moment you leave, and a healer's whole match is in them.
  local d = db()
  local ranking = self:TeamRanking()
  if d then
    d.lastMatch = {
      bg = bg, won = won, at = (time and time()) or 0,
      ranking = ranking and {
        teamSize = ranking.teamSize,
        damage = slim(ranking.damage), healing = slim(ranking.healing),
        kills = slim(ranking.kills),
      } or nil,
    }
  end
  LP:Fire("BG_RESULT", bg, won)
  return won
end

function N:Lifetime()
  local d = db()
  local hk = 0
  if GetPVPLifetimeStats then hk = (GetPVPLifetimeStats()) or 0 end
  local wins, losses = 0, 0
  local byBG = {}
  if d then
    for id, r in pairs(d.results) do
      wins = wins + (r.wins or 0)
      losses = losses + (r.losses or 0)
      byBG[id] = { wins = r.wins or 0, losses = r.losses or 0 }
    end
  end
  return {
    honorableKills = hk,
    honorableKillsAreLifetime = true,
    wins = wins,
    losses = losses,
    -- Deliberately explicit. A player who has been 80 for a year and installed
    -- this yesterday must not be shown "3 wins" as their career record.
    winsAreLifetime = false,
    byBG = byBG,
    longestStreak = self:LongestStreak(),
  }
end

-- ---------------------------------------------------------------------------
-- Alerts
-- ---------------------------------------------------------------------------

function N:Alert(kind, msg)
  local d = db()
  if not d then return end
  -- One switch per event kind, gating BOTH the chat line and the sound.
  -- Gating only the sound meant "kill alerts off" still spammed chat on
  -- every kill, which is not what off means.
  if not d.sounds[kind] then return end
  if msg then LP:Print(msg) end
  if PlaySoundFile then
    -- PlaySoundFile returns nothing on 3.3.5a: a bad path fails silently and
    -- there is no way to detect it, which is why the path is a constant.
    PlaySoundFile(SOUND)
  end
end

function N:PrintSummary()
  local s = self:Lifetime()
  LP:Print(string.format("honorable kills: %d (lifetime, from the server)",
                         s.honorableKills))
  LP:Print(string.format("battlegrounds since install: %d won, %d lost",
                         s.wins, s.losses))
  LP:Print(string.format("killstreak: %d now, %d best",
                         self:CurrentStreak(), self:LongestStreak()))

  local top = self:TopNemeses(3)
  if #top == 0 then
    LP:Print("no nemeses yet -- nobody has killed you more than you killed them.")
  else
    LP:Print("top nemeses:")
    for i = 1, #top do
      local t = top[i]
      LP:Print(string.format("  %d. %s%s -- %d death(s) to %d kill(s)",
        i, t.name, t.guild and (" <" .. t.guild .. ">") or "",
        t.deaths or 0, t.kills or 0))
    end
  end

  local known, total = self:GuildCoverage()
  if total > 0 then
    LP:Print(string.format("enemy guilds known: %d of %d (only those you target)",
                           known, total))
  end
end

-- ---------------------------------------------------------------------------
-- Module
-- ---------------------------------------------------------------------------

local POLL_SECONDS = 3

-- What the companion uploads. Only the fields the board needs, and the
-- lifetime/since-install distinction is preserved on the wire so the server
-- cannot accidentally present one as the other.
function N:Payload()
  local st = self:Lifetime()
  local out = {
    honorableKills = st.honorableKills,
    wins = st.wins,
    losses = st.losses,
    longestStreak = st.longestStreak,
    winsAreLifetime = false,
    nemeses = {},
  }
  local top = self:TopNemeses(10)
  for i = 1, #top do
    out.nemeses[i] = {
      name = top[i].name, kills = top[i].kills,
      deaths = top[i].deaths, guild = top[i].guild,
    }
  end
  return out
end

-- The two meters a match is judged by, from the live scoreboard or from the
-- saved final standing. Saved copies carry no band, so it is recomputed.
local function standingRows(rows, r, live)
  local function bandOf(x)
    return x.band or (x.pct and LP.data and LP.data.BandFor and LP.data.BandFor(x.pct)) or nil
  end
  local d = r.damage
  if d then
    rows[#rows + 1] = {
      kind = "meter", label = "Damage", pct = d.pct, band = bandOf(d),
      value = LP.util.FormatNumber(d.value),
      note = d.pct and string.format("%d of %d", d.place, d.of)
             or "no one to compare against",
    }
  end
  local hl = r.healing
  if hl then
    if hl.participating then
      rows[#rows + 1] = {
        kind = "meter", label = "Healing", pct = hl.pct, band = bandOf(hl),
        value = LP.util.FormatNumber(hl.value),
        note = hl.pct and string.format("%d of %d healers", hl.place, hl.of)
               or (live and "only healer so far" or "the only healer"),
      }
    else
      -- Ranking a rogue's zero healing against a team of zeroes would look
      -- like information and be none. Say why the bar is absent instead.
      rows[#rows + 1] = { kind = "stat", label = "Healing", value = "--",
        note = "not healing this match" }
    end
  end
end

function N:Dashboard()
  local s = self:Lifetime()
  local rows = {}

  -- Live standing FIRST, when there is one: in a battleground this is the
  -- thing you actually want to glance at, and lifetime totals are not.
  local live = self:TeamRanking()
  if live then
    rows[#rows + 1] = { kind = "header", text = "This battleground" }
    standingRows(rows, live, true)
  elseif self:InBattleground() then
    -- In a match, no scoreboard yet. It is requested every few seconds; this
    -- should last moments, and if it does not, the player can force it.
    rows[#rows + 1] = { kind = "header", text = "This battleground" }
    -- Two short rows: the panel draws one unwrapped line per row.
    rows[#rows + 1] = { kind = "empty", text = "Waiting for the scoreboard (requested; a few seconds)." }
    rows[#rows + 1] = { kind = "empty", text = "If it never fills in, open the scoreboard once (H)." }
  else
    -- The scoreboard, and the live meters with it, is gone the moment you
    -- leave. The final standing was saved when the match ended.
    local d = db()
    local last = d and d.lastMatch
    if last and last.ranking then
      rows[#rows + 1] = { kind = "header",
        text = "Last battleground: " .. tostring(last.bg or "?")
               .. (last.won and " -- won" or " -- lost") }
      standingRows(rows, last.ranking, false)
    end
  end

  rows[#rows + 1] = { kind = "header", text = "Battlegrounds" }
  local tail = {
    { kind = "stat", label = "Honorable kills", value = s.honorableKills,
      note = "lifetime" },
    { kind = "stat", label = "Record", value = s.wins .. "W  " .. s.losses .. "L",
      -- Never let this read as a career record: we only saw matches since
      -- the addon was installed.
      note = "since install" },
    { kind = "stat", label = "Killstreak",
      value = self:CurrentStreak() .. "  (best " .. self:LongestStreak() .. ")" },
  }
  for i = 1, #tail do rows[#rows + 1] = tail[i] end

  local top = self:TopNemeses(3)
  if #top > 0 then
    local items = {}
    for i = 1, #top do
      local t = top[i]
      items[i] = {
        text = t.name .. (t.guild and (" <" .. t.guild .. ">") or ""),
        sub = (t.deaths or 0) .. "d / " .. (t.kills or 0) .. "k",
      }
    end
    rows[#rows + 1] = { kind = "list", title = "Top nemeses", items = items }
  else
    -- A nemesis is someone who has killed you more than you killed them, so
    -- a healer who never died has none -- and that is not a fault. When you
    -- DID die and nobody was blamed, say why rather than leaving a blank.
    local why = "nobody has killed you more than you have killed them."
    if unattributedDeaths > 0 then
      why = string.format("you died %d time(s) %s with no player on the last hit.",
          unattributedDeaths, self:InBattleground() and "this match" or "last match")
    end
    rows[#rows + 1] = { kind = "empty", text = "No nemeses yet -- " .. why }
    if unattributedDeaths > 0 then
      rows[#rows + 1] = { kind = "empty",
        text = "(pets, totems and falls do not count, so nobody could be blamed)" }
    end
  end

  -- Achievements, newest first, with their icons.
  if LP.PvP and LP.PvP.EarnedAchievements then
    local ok, earned = pcall(function() return LP.PvP:EarnedAchievements() end)
    if ok and type(earned) == "table" then
      local items = {}
      for i = 1, #earned do
        local a = earned[i]
        if a.earned then
          items[#items + 1] = {
            text = a.name,
            sub = a.desc,
            icon = LP.data and LP.data.AchievementIcon and
                   LP.data.AchievementIcon(a.id) or nil,
            -- Earned achievements get the gold of a perfect parse; it is the
            -- one place in the addon where a fixed colour beats a computed one.
            colour = LP.data and LP.data.BANDS and LP.data.BANDS[#LP.data.BANDS],
          }
        end
      end
      if #items > 0 then
        rows[#rows + 1] = { kind = "list", title = "Achievements", items = items }
      end
    end
  end

  local known, total = self:GuildCoverage()
  if total > 0 then
    rows[#rows + 1] = { kind = "stat", label = "Enemy guilds known",
      value = known .. " of " .. total, note = "only those you target" }
  end
  return rows
end

LP:RegisterModule({
  id = "nemesis",
  title = "Nemesis",
  desc = "Battleground roster, nemesis alerts, flags, kills and streaks.",
  default = true,
  Dashboard = function() return N:Dashboard() end,

  OnEnable = function()
    N:Init()

    -- Who is hitting ME. PLAYER_DEAD carries no killer, so the last player
    -- to land damage on us is the attribution -- and nothing set this field
    -- before, which meant every death recorded a nil enemy and "who keeps
    -- killing you" never populated from a real death. Cheapest reject first:
    -- this runs for every damage line in a 40-player battleground.
    N.myGUID = (UnitGUID and UnitGUID("player")) or nil
    LP:OnCombatLog("nemesis",
      { "SWING_DAMAGE", "SPELL_DAMAGE", "RANGE_DAMAGE", "SPELL_PERIODIC_DAMAGE" },
      function(_, _, srcGUID, srcName, _, dstGUID)
        if dstGUID ~= N.myGUID then return end
        if srcName and util.IsPlayerGUID(srcGUID) then N.lastAttacker = srcName end
      end)

    LP:OnCombatLog("nemesis", { "PARTY_KILL" },
      function(_, _, _, _, _, dstGUID, dstName)
        -- PARTY_KILL fires for the KILLER only and is unicast to their group,
        -- so this is our kill. But it fires for EVERY kill, mobs included --
        -- without the player check, an afternoon of grinding would inflate
        -- your killstreak and your PvP record.
        if dstName and util.IsPlayerGUID(dstGUID) then N:RecordKill(dstName) end
      end)

    LP:RegisterEvent("PLAYER_DEAD", "nemesis", function()
      N:RecordDeath(N.lastAttacker)
      N.lastAttacker = nil   -- consumed; the next death needs a fresh hit
    end)

    LP:RegisterEvent("PLAYER_TARGET_CHANGED", "nemesis", function()
      N:LearnGuild("target")
    end)
    LP:RegisterEvent("UPDATE_MOUSEOVER_UNIT", "nemesis", function()
      N:LearnGuild("mouseover")
    end)

    for _, ev in ipairs({ "CHAT_MSG_BG_SYSTEM_ALLIANCE",
                          "CHAT_MSG_BG_SYSTEM_HORDE",
                          "CHAT_MSG_BG_SYSTEM_NEUTRAL" }) do
      LP:RegisterEvent(ev, "nemesis", function(msg) N:OnBGChat(msg) end)
    end

    LP:RegisterEvent("PLAYER_ENTERING_BATTLEGROUND", "nemesis", function()
      N:Init()
    end)
    -- The scoreboard refresh is where the winner appears. The poll above
    -- requests one every few seconds, so this fires throughout a match.
    LP:RegisterEvent("UPDATE_BATTLEFIELD_SCORE", "nemesis", function()
      N:CheckWinner()
    end)

    -- Arenas share the scoreboard API but not the point of any of this.
    N.pollJob = LP:Schedule(POLL_SECONDS, function()
      if not N:InBattleground() then return end
      -- Ask BEFORE looking. The scoreboard is empty until something requests
      -- it from the server, and this used to request only once scores
      -- existed -- so nothing appeared until the player opened Blizzard's
      -- scoreboard by hand once. (Blizzard's frame requests it every single
      -- frame while open; every few seconds is polite.)
      -- ...but NOT once the match is decided. Every score update makes
      -- Blizzard's WorldStateScoreFrame_Update show the final scoreboard
      -- again (WorldStateFrame.lua:513, no is-shown check), so requesting
      -- after the end would re-open it every three seconds after the player
      -- closed it. The final data is static; nothing is lost by stopping.
      if GetBattlefieldWinner and GetBattlefieldWinner() ~= nil then return end
      if RequestBattlefieldScoreData then RequestBattlefieldScoreData() end
      if GetNumBattlefieldScores and GetNumBattlefieldScores() > 0 then N:PollRoster() end
    end)
  end,

  OnDisable = function()
    -- The event router drops the handlers; the polling job is ours to stop.
    if N.pollJob then LP:Unschedule(N.pollJob); N.pollJob = nil end
  end,
})
