-- LevelPace :: Baseline (generated)
--
-- OVERWRITTEN by the LevelPace uploader. Do not hand-edit.
--
-- The addon cannot make network requests, so it cannot fetch the global
-- distribution itself. Instead the uploader downloads it and rewrites this
-- file; the client loads it from the TOC on the next /reload. That is the
-- same shipped-data-file trick Questie and friends use.
--
-- Shape:
--   LevelPaceBaseline = {
--     fetched  = <unix seconds>,
--     source   = "<server url>",
--     players  = <number of characters in the sample>,
--     overall  = { <levels-per-hour>, ... },   -- all levels pooled
--     byLevel  = { [71] = { <levels-per-hour>, ... }, ... },
--   }
--
-- Absent or empty means "no global data", and the gauge falls back to
-- scoring against your own history. That is the default state and it is a
-- perfectly good one.

LevelPaceBaseline = nil
