#!/usr/bin/env python3
"""Generate LevelPace/Data/Rares.lua from data/rares_335.json.

The JSON is the source of truth (extracted from WotLK creature_template,
rank 4 = rare, rank 2 = rare elite). Regenerate with:  python3 tools/gen_rares.py
"""
import json, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = json.loads((root / "data" / "rares_335.json").read_text())

rows = sorted(((int(k), v) for k, v in src.items()), key=lambda kv: kv[0])

out = [
    "-- LevelPace :: Data/Rares",
    "--",
    "-- Rare and rare-elite creature entries for 3.3.5a, keyed by NPC entry id.",
    "-- rank 4 = rare, rank 2 = rare elite.",
    "--",
    "-- GENERATED by tools/gen_rares.py from data/rares_335.json -- do not edit.",
    "-- Custom server rares are not here by design; they are learned at runtime",
    "-- from UnitClassification and stored separately.",
    "",
    "local LP = _G.LevelPace",
    "LP.data = LP.data or {}",
    "",
    "LP.data.RARES = {",
]
for entry, v in rows:
    name = v["name"].replace("\\", "\\\\").replace('"', '\\"')
    out.append('  [%d] = { name = "%s", rank = %d },' % (entry, name, v["rank"]))
out += [
    "}",
    "",
    "LP.data.RARE_COUNT = %d" % len(rows),
    "",
]

dst = root / "LevelPace" / "Data" / "Rares.lua"
dst.write_text("\n".join(out))
print("wrote %s: %d entries" % (dst.relative_to(root), len(rows)))
